ARG ROS_DISTRO=humble
ARG IMAGE_NAME=ros
FROM ${IMAGE_NAME}:${ROS_DISTRO} as cache-stage

WORKDIR /workspace
RUN echo "repositories:" >> workspace.repos

ARG REPOS_FILE=workspace.repos
ADD ${REPOS_FILE} workspace.repos

ARG APT_SERVER=ftp.jaist.ac.jp/pub/Linux
RUN sed -i "s@archive.ubuntu.com@$APT_SERVER@g" /etc/apt/sources.list
RUN vcs import . < workspace.repos
RUN apt update && rosdep install -iy --from-paths . --skip-keys $(colcon list -n | tr '\n' ',') && \
    apt-get clean \
    && rm -rf /var/lib/apt/lists/*
