ARG ROS_DISTRO=humble
FROM ros:${ROS_DISTRO} as build-cacher-stage

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get install -y \
    apt-cacher-ng\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir workspace
WORKDIR /workspace

ARG REPOS_FILE=workspace.repos
ADD ${REPOS_FILE} ${REPOS_FILE}
RUN rosdep update
RUN vcs import . < ${REPOS_FILE}
RUN apt-get update && \
    rosdep update && \
    rosdep install -iy --from-paths .
