name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - ros2_pkg_builder/**
      - tests/**
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/bake-action@v3
        with:
          push: true
          workdir: ros2_pkg_builder/docker
          files: |
            ./docker-bake.hcl
  build_python_packages:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.12"]
        poetry-version: ["1.5.1"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install
        run: poetry install
      - name: prepare
        run: poetry run task prepare
      - name: lint
        run: poetry run task lint
