name: pytest
on:
  pull_request:
    paths:
      - .github/workflows/pytest.yaml
      - amber/**
      - tests/**
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  release:
    types: [published]

jobs:
  pytest:
    name: pytest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10.6"]
        poetry-version: ["1.5.1"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install
        run: poetry install --with=dev
      - name: lint
        run: poetry run task lint
      - name: test
        run: poetry run task test
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./_htmlcov/coverage.xml
      #     flags: pytest # optional
      #     name: codecov-umbrella # optional
      #     fail_pytest_if_error: true # optional (default = false)
      #     verbose: true # optional (default = false)
      #     token: ${{ secrets.CODECOV_TOKEN }}
